# -*- coding: utf-8 -*-
"""Copy of ED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPnXUkKIw1ohBy0wRVlIAroo26nUUFqv
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import sympy

sympy.init_printing(use_latex="mathjax")

x,y,r = sympy.symbols("x y r")
f = sympy.Function("funcion")

densidad = sympy.Symbol("densidad")
ln_densidad = sympy.ln(densidad)

r = f(x,y)
r_x = r.diff(x)
r_y = r.diff(y)
ecuacion = sympy.Eq(-10*r_x + 1*r_y + ln_densidad)
print(ecuacion)

sol = sympy.pdsolve(ecuacion)
print(sol)